### ISSUE TITLE
/example generated jar doesn't include gwt js, css etc.

### ISSUE THREAD

**Issue by francisoud** [levigo/gwt-spring-boot-starter#12]
Hi,

In the /example project, the files generated by gwt compiler under example/src/main/webapp are not included in target/gwt-spring-boot-starter-example-1.0-SNAPSHOT.jar

### Steps to reproduce
`gwt-spring-boot-starter>mvn clean package`

`gwt-spring-boot-starter\example>java -jar target\gwt-spring-boot-starter-example-1.0-SNAPSHOT.jar`
:heavy_check_mark: http://localhost:8080/ work as expected 

Either move one directory up (in target):
`gwt-spring-boot-starter\example\target>java -jar gwt-spring-boot-starter-example-1.0-SNAPSHOT.jar`
:x: http://localhost:8080/ fails to load http://localhost:8080/springdemo/springdemo.nocache.js (404)
![image](https://user-images.githubusercontent.com/23797/160553672-89195285-8bad-4de3-87b2-41f9ec253836.png)

Same error if you move the generated jar to a different directory
`C:\tmp>java -jar gwt-spring-boot-starter-example-1.0-SNAPSHOT.jar`
:x: http://localhost:8080/ fails to load http://localhost:8080/springdemo/springdemo.nocache.js (404)

### Problem
This is because the generated files by the gwt compiler in example/src/main/webapp are not included in the jar file.
For some reason (I didn't found where) spring-boot find the springdemo/springdemo.nocache.js by using some kind of relative path (../springdemo/springdemo.nocache.js) when we launch the jar from the appropriate place but it can't work when deployed in production.

### Additional information

  >mvn --version
  Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
  Maven home: C:\softwares\maven\apache-maven-3.8.4
  Java version: 17.0.2, vendor: Oracle Corporation, runtime: C:\softwares\java\openjdk-17.0.2
  Default locale: fr_FR, platform encoding: Cp1252
  OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by francisoud** [comment]
I tried various solutions.
The main problem is that the gwt-maven-plugin is build on the idea that the maven project is packaged as a war.
Since spring-boot can now repackage jar but also war. The easiest solution is to change the packaging to war.
I'll provide a PR :)

**Comment by werthdavid** [comment]
Thanks for sharing.
We experienced the same issue in our projects as well. WAR packaging is one option, especially if you need JSPs then it is the only option.
An alternative is to place static resources to src/main/resources/static and not src/main/webapp then packaging as JAR works as well.
PRs are much appreciated!

**Comment by francisoud** [comment]
I must have missed something the PR doesn't show up here :( 
So provided the link: https://github.com/levigo/gwt-spring-boot-starter/pull/13
