### ISSUE TITLE
v1.1.2 not released in maven central ?

### ISSUE THREAD

**Issue by francisoud** [levigo/gwt-spring-boot-starter#9]
Thanks for creating [gwt-spring-boot-starter](https://github.com/levigo/gwt-spring-boot-starter) it seems to be exactly what I'm looking for :) 
I'm trying to use it but I'm a bit confuse according the [README.md](https://github.com/levigo/gwt-spring-boot-starter/blob/master/README.md?plain=1#L18) the v1.1.2 should be use but I can't find it ?

I checked:
- https://oss.sonatype.org/#nexus-search;quick~gwt-spring-boot-starter
- https://mvnrepository.com/artifact/org.jadice.gwt.spring/gwt-spring-boot-starter

I only found v1.0.16
Am I missing something ? Is it somewhere else ?

Thanks

**Comment by werthdavid** [comment]
Hey @francisoud 
that's right, we're currently publishing the artifact to our internal Nexus only... I'll see what we can do so it will be published to maven central. Until then you can build v1.1.2 with the source if that is an option for you.

Kind regards,
David

**Comment by francisoud** [comment]
Thanks @werthdavid 
If you can push it to maven central it would be better/easier but v1.0.16 seems to be enough for the moment ;)
But I didn't tried [DevModeLauncher.java](https://github.com/levigo/gwt-spring-boot-starter/compare/v1.0.19...v1.1.2#diff-e113ec1256e3d86f53910d2f8b1999434477ff040b791efa4ee4427fdadaa345) yet.
It seems to be the main file that changed since v1.0.9 (I didn't found 1.0.16 tag)

ps: I might suggest some improvement to the example project next week because gwt compiled js don't seems to be packaged as part of the spring 'fat' jar (I'll create a fork/PR);

**Comment by werthdavid** [comment]
Should be fixed

**Comment by francisoud** [comment]
perfect v1.1.6 
https://mvnrepository.com/artifact/org.jadice.gwt.spring/gwt-spring-boot-starter/1.1.6
